#!/bin/bash
echo -e "\e[33m"
echo -e "rm ${1:-solution}"
rm ${1:-solution}
echo -e "g++-13 -std=c++23 -Wall -Wshadow -g -fsanitize=address,undefined -fuse-ld=gold -DDEBUG -o ${1:-solution} ${1:-solution}.cpp"
g++-13 -std=c++23 -Wall -Wshadow -g -fsanitize=address,undefined -fuse-ld=gold -DDEBUG -o ${1:-solution} ${1:-solution}.cpp
echo -e "chmod +x ${1:-solution}"
chmod +x ${1:-solution}
echo -e "\e[39m"
