#!/bin/bash
set -e
sudo mount -t tmpfs -o size=1024m tmpfs /mnt/tmpfs
tc=1
while : ; do
    echo -e "\e[34m./${1:-gen.py} $tc > /mnt/tmpfs/input.txt\e[39m"
    ./${1:-gen.py} $tc > /mnt/tmpfs/input.txt
    if [ -f "solution" ]; then
        echo -e "\e[34m./${2:-solution} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt\e[39m"
        if ! ./${2:-solution} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt ; then
            echo -e "\e[31msolution runtime error\e[39m"
            echo -e "\e[33minput:\e[39m"
            cat /mnt/tmpfs/input.txt
            break
        fi
    else
        echo -e "\e[34m./${2:-solution.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt\e[39m"
        if ! ./${2:-solution.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt ; then
            echo -e "\e[31msolution runtime error\e[39m"
            echo -e "\e[33minput:\e[39m"
            cat /mnt/tmpfs/input.txt
            break
        fi
    fi
    if [ -f "brute" ]; then
        echo -e "\e[34m./${2:-brute} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt\e[39m"
        if ! ./${2:-brute} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt ; then
            echo -e "\e[31mbrute runtime error\e[39m"
            echo -e "\e[33minput:\e[39m"
            cat /mnt/tmpfs/input.txt
            break
        fi
    else
        echo -e "\e[34m./${3:-brute.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt\e[39m"
        if ! ./${3:-brute.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt ; then
            echo -e "\e[31mbrute runtime error\e[39m"
            echo -e "\e[33minput:\e[39m"
            cat /mnt/tmpfs/input.txt
            break
        fi
    fi
    if ! cmp --silent /mnt/tmpfs/output.txt /mnt/tmpfs/expected.txt ; then
        echo -e "\e[31mtest failed\e[39m"
        echo -e "\e[33minput:\e[39m"
        cat /mnt/tmpfs/input.txt
        echo -e "\e[33moutput:\e[39m"
        cat /mnt/tmpfs/output.txt
        echo -e "\e[33mexpected:\e[39m"
        cat /mnt/tmpfs/expected.txt
        cp /mnt/tmpfs/input.txt ./input.txt
        cp /mnt/tmpfs/output.txt ./output.txt
        cp /mnt/tmpfs/expected.txt ./expected.txt
        break
    fi
    echo -e "\e[32m$((tc++)) test cases passed\e[39m"
done
