#!/bin/bash
rm $1
echo -e "\e[33mcoan source --implicit $1.cpp > $1_clean.cpp"
coan source --implicit $1.cpp > $1_clean.cpp
echo -e "\e[33mg++ -std=c++17 -Wall -DDEBUG -o $1 $1_clean.cpp"
g++ -std=c++17 -Wall -DDEBUG -o $1 $1_clean.cpp
chmod +x $1
echo -e "\e[33m./$1 < input.txt"
echo -e "\e[39m"
./$1 < input.txt
